//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_details.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_info
    {
        public int Stu_Id { get; set; }
        public string Student_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Student_Course { get; set; }
        public string Section { get; set; }
        public string Student_Address { get; set; }
    }
}
